services:
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pissicat'
      MYSQL_DATABASE: 'master'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pissicat'
    volumes:
      - './data:/var/lib/mysql'
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true